import { Request, Response } from "express";
import query from "./db";

class ProdPrepController {
    public async create(req: Request, res: Response): Promise<Response> {
        const {
            pp_produto,
            pp_preparacao,
            pp_energia,
            pp_proteina,
            pp_lipidios,
            pp_carboidrato,
            pp_fibra,
            pp_colesterol,
            pp_agsaturado,
            pp_agmono,
            pp_agpoli,
            pp_aglinoleico,
            pp_aglinolenico,
            pp_agtranstotal,
            pp_acucartotal,
            pp_acucaradicao,
            pp_calcio,
            pp_magnesio,
            pp_manganes,
            pp_fosforo,
            pp_ferro,
            pp_sodio,
            pp_sodioadicao,
            pp_potassio,
            pp_cobre,
            pp_zinco,
            pp_selenio,
            pp_retinol,
            pp_vitamina_a,
            pp_tiamina,
            pp_riboflavina,
            pp_niacina,
            pp_niacina_ne,
            pp_piridoxina,
            pp_cobalamina,
            pp_folato,
            pp_vitamina_d,
            pp_vitamina_e,
            pp_vitamina_c
        } = req.body;

        const r: any = await query(
            `INSERT INTO prod_prep (
                pp_produto,
                pp_preparacao,
                pp_energia,
                pp_proteina,
                pp_lipidios,
                pp_carboidrato,
                pp_fibra,
                pp_colesterol,
                pp_agsaturado,
                pp_agmono,
                pp_agpoli,
                pp_aglinoleico,
                pp_aglinolenico,
                pp_agtranstotal,
                pp_acucartotal,
                pp_acucaradicao,
                pp_calcio,
                pp_magnesio,
                pp_manganes,
                pp_fosforo,
                pp_ferro,
                pp_sodio,
                pp_sodioadicao,
                pp_potassio,
                pp_cobre,
                pp_zinco,
                pp_selenio,
                pp_retinol,
                pp_vitamina_a,
                pp_tiamina,
                pp_riboflavina,
                pp_niacina,
                pp_niacina_ne,
                pp_piridoxina,
                pp_cobalamina,
                pp_folato,
                pp_vitamina_d,
                pp_vitamina_e,
                pp_vitamina_c
            ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36, $37, $38, $39)
            RETURNING pp_produto`,
            [
                pp_produto,
                pp_preparacao,
                pp_energia,
                pp_proteina,
                pp_lipidios,
                pp_carboidrato,
                pp_fibra,
                pp_colesterol,
                pp_agsaturado,
                pp_agmono,
                pp_agpoli,
                pp_aglinoleico,
                pp_aglinolenico,
                pp_agtranstotal,
                pp_acucartotal,
                pp_acucaradicao,
                pp_calcio,
                pp_magnesio,
                pp_manganes,
                pp_fosforo,
                pp_ferro,
                pp_sodio,
                pp_sodioadicao,
                pp_potassio,
                pp_cobre,
                pp_zinco,
                pp_selenio,
                pp_retinol,
                pp_vitamina_a,
                pp_tiamina,
                pp_riboflavina,
                pp_niacina,
                pp_niacina_ne,
                pp_piridoxina,
                pp_cobalamina,
                pp_folato,
                pp_vitamina_d,
                pp_vitamina_e,
                pp_vitamina_c
            ]
        );
        return res.json(r);
    }

    public async list(_: Request, res: Response): Promise<Response> {
        const r: any = await query(
            "SELECT * FROM prod_prep ORDER BY pp_produto"
        );
        return res.json(r);
    }

    public async delete(req: Request, res: Response): Promise<Response> {
        const { pp_produto } = req.body; // id do registro a ser excluído
        const r: any = await query(
            "DELETE FROM prod_prep WHERE pp_produto = $1", [pp_produto]
        );
        return res.json(r);
    }

    public async update(req: Request, res: Response): Promise<Response> {
        const {
            pp_produto,
            pp_preparacao,
            pp_energia,
            pp_proteina,
            pp_lipidios,
            pp_carboidrato,
            pp_fibra,
            pp_colesterol,
            pp_agsaturado,
            pp_agmono,
            pp_agpoli,
            pp_aglinoleico,
            pp_aglinolenico,
            pp_agtranstotal,
            pp_acucartotal,
            pp_acucaradicao,
            pp_calcio,
            pp_magnesio,
            pp_manganes,
            pp_fosforo,
            pp_ferro,
            pp_sodio,
            pp_sodioadicao,
            pp_potassio,
            pp_cobre,
            pp_zinco,
            pp_selenio,
            pp_retinol,
            pp_vitamina_a,
            pp_tiamina,
            pp_riboflavina,
            pp_niacina,
            pp_niacina_ne,
            pp_piridoxina,
            pp_cobalamina,
            pp_folato,
            pp_vitamina_d,
            pp_vitamina_e,
            pp_vitamina_c
        } = req.body;

        const r: any = await query(
            `UPDATE prod_prep SET
                pp_preparacao = $2,
                pp_energia = $3,
                pp_proteina = $4,
                pp_lipidios = $5,
                pp_carboidrato = $6,
                pp_fibra = $7,
                pp_colesterol = $8,
                pp_agsaturado = $9,
                pp_agmono = $10,
                pp_agpoli = $11,
                pp_aglinoleico = $12,
                pp_aglinolenico = $13,
                pp_agtranstotal = $14,
                pp_acucartotal = $15,
                pp_acucaradicao = $16,
                pp_calcio = $17,
                pp_magnesio = $18,
                pp_manganes = $19,
                pp_fosforo = $20,
                pp_ferro = $21,
                pp_sodio = $22,
                pp_sodioadicao = $23,
                pp_potassio = $24,
                pp_cobre = $25,
                pp_zinco = $26,
                pp_selenio = $27,
                pp_retinol = $28,
                pp_vitamina_a = $29,
                pp_tiamina = $30,
                pp_riboflavina = $31,
                pp_niacina = $32,
                pp_niacina_ne = $33,
                pp_piridoxina = $34,
                pp_cobalamina = $35,
                pp_folato = $36,
                pp_vitamina_d = $37,
                pp_vitamina_e = $38,
                pp_vitamina_c = $39
            WHERE pp_produto = $1`,
            [
                pp_produto,
                pp_preparacao,
                pp_energia,
                pp_proteina,
                pp_lipidios,
                pp_carboidrato,
                pp_fibra,
                pp_colesterol,
                pp_agsaturado,
                pp_agmono,
                pp_agpoli,
                pp_aglinoleico,
                pp_aglinolenico,
                pp_agtranstotal,
                pp_acucartotal,
                pp_acucaradicao,
                pp_calcio,
                pp_magnesio,
                pp_manganes,
                pp_fosforo,
                pp_ferro,
                pp_sodio,
                pp_sodioadicao,
                pp_potassio,
                pp_cobre,
                pp_zinco,
                pp_selenio,
                pp_retinol,
                pp_vitamina_a,
                pp_tiamina,
                pp_riboflavina,
                pp_niacina,
                pp_niacina_ne,
                pp_piridoxina,
                pp_cobalamina,
                pp_folato,
                pp_vitamina_d,
                pp_vitamina_e,
                pp_vitamina_c
            ]
        );
        return res.json(r);
    }
}

export default new ProdPrepController();
